services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db # Named volumes
    # environment:
    #   # Assigning our key value pairs like so or wqe can specify the path to our file
    #   MONGO_INITDB_ROOT_USERNAME: olly
    #   MONGO_INITDB_ROOT_PASSWORD: password
    env_file:
      # Here we use the env_file syntax and specify the relavtive path
      - ./env/mongo.env
    # NOTE: We dont need to specify the networks as docker compose will automatically compile all of our services specified in this compose file into their own enviorment.
    # networks:
    #   - goals-net
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      # Named volumes
      - logs:/app/logs
      # NOTE: Bind mounts And Anoynmous volumes are not/can't be specified in the same way as volumes
      - ./backend:/app # No need to specify the absolute path or $(pwd)
      # Anonymous volumes
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - backend
# Top Level Volumes key - Any named volumes we use have to be defined here also
volumes:
  # Anonymous and bind mounts don't need to be specified here
  data: # We leave it emoty like so but we are just making docker aware of the volume
  logs: # Reference to our backend named logs volume
